PiCamera framerate fixed on lower value
When default framerate was used, following exception occured (at least when using Raspberrry HQ camera 1.0):

picamera.exc.PiCameraRuntimeError: No data recevied from sensor. Check all connections, including the SUNNY chip on the camera board

With framerate set to 10, it works.